# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'  # imposta un deployment target compatibile con la maggior parte dei moduli nativi

prepare_react_native_project!

target 'TaskManager' do
  config = use_native_modules!

  # Non serve usare use_frameworks! a meno che tu non abbia librerie Swift che lo richiedono
  # Nel tuo caso SQLite è compatibile senza use_frameworks!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # questo serve a risolvere eventuali problemi con librerie C++ o Swift bridge
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
